### ISSUE TITLE
Sujet, utilité, effet rebond

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Swapp#1]
Merci pour votre document @AlixByr, @MissJeanneB.

Votre argumentaire est de bonne qualité, bravo !
Attention, cependant, il y a quelques coquilles ("là que", "écologique.L'impact").

Comme le texte est bien, il ne s'agit pas de le changer en profondeur, mais quelques phrases en plus le rendraient encore meilleur : 

- Vous pourriez peut-être ajouter une phrase ou deux dans la partie sur l'effet de la numérisation en expliquant comment vous allez éviter dans votre conception l'effet rebond (qui effectivement est bien plus important que la consommation de l'application elle-même).
- Vous n'évoquez pas du tout ce qu'étaient les pratiques de seconde main avant l'arrivée du numérique. Qu'est-ce que ce changement a apporté en bien ? en mal ?

**Comment by MissJeanneB** [comment]
C'est corrigé
