### ISSUE TITLE
Scénarios

### ISSUE THREAD

**Issue by benel** [UTT-GL03/Swapp#2]
Merci pour vos scénarios @MissJeanneB et @AlixByr.
Ils sont plutôt bien, mais par contre ils ne vont pas jusqu'à l'acte d'achat. 
Je peux en imaginer les raisons, mais si vous n'expliquez pas pourquoi, le lecteur pourrait en être un peu étonné.

Par ailleurs, c'est un peu paradoxal de présenter une plateforme d'économie circulaire et de ne pas avoir de scénario pour l'autre côté du "cercle" (au moins le dépôt d'une annonce)... Ce ne sera probablement pas le scénario prioritaire, mais ce serait bien de le prévoir quand même puisqu'il est nécessaire pour un véritable MVP.

**Comment by MissJeanneB** [comment]
C'est corrigé
